spring:
  application:
    name: pt-app
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/pt_db
    username: spring
    password: spring
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

